### ISSUE TITLE
Do Sankoff on the history DAG

### ISSUE THREAD

**Issue by willdumm** [matsengrp/historydag#27]
Doing true Sankoff on the history DAG in a dynamic programming sense requires keeping track of too many alternative cost vectors below each node (potentially one for each subtree below that node). However, in order to make modifications freely to the DAG, we must have a way of adjusting node labels correctly after those modifications.

As a starting point, imagine taking a large hDAG containing many maximally parsimonious trees, and unlabeling it. Remember that doing so will collapse nodes which were distinguished only by their sequences, and may add many topologies to the DAG that do not admit a maximally parsimonious labeling.

As an experiment our goal will be to reconstruct the original MP hDAG as much as we can by computing optimal sequences for the internal nodes in the DAG. This process must involve 'exploding' the nodes that were merged when the DAG was unlabeled.

One way we could recompute sequences at internal nodes of the DAG is by performing Sankoff on (up to) one tree containing each node of the DAG, and using the reconstructed sequence as the new label for each DAG node contained in that tree. Since each tree contains many of the nodes in the DAG we'll have to do Sankoff on many fewer trees than there are nodes in the DAG.

Using node supports, there may be a way of easily minimizing the number of trees that Sankoff must be performed on. For example, we could start by finding sequences for the least-supported nodes, since trees containing these nodes will also contain lots of well-supported nodes. This may bias the resulting DAG towards strange trees in some way, though.

Although the upward pass of Sankoff must be done on the whole tree, if we only care about the sequence on a single node, the downward pass may simply follow a direct path from the root to the node of interest, avoiding the expense of reconstructing sequences on every node in the tree. However, we may want to reconstruct sequences on all nodes, to get more alternative sequences for nodes which may have already been labeled.

**Comment by marybarker** [comment]
Here's a preflight for the DAG-Sankoff project. 
[dag_sankoff_preflight.md](https://github.com/matsengrp/historydag/files/9491615/dag_sankoff_preflight.md)
